### ISSUE TITLE
pseudo selectors compilation problem

### ISSUE THREAD

**Issue by sakhram** [wizardpisces/tiny-sass-compiler#11]
Hello,
first thanks for the job!

**Second, It seems there is a scss compilation problem for pseudo-classes:**
```
.myClass{
    &:hover{
    color: red;
    }
}
```
**should compile to:**
```
.myClass:hover{
  color:red;
}
```

**but it compiles to**
```
.myClass :hover{
  color:red;
}
```
with a space between class and pseudo class
And the problem seems to be the same for all pseudo-classes. In fact, anything sticked to the pseudo-class is ignored (even real classes, like .example:hover compiles to :hover).

Am I mistaking something or is this a real issue?
Thanks!

**Comment by wizardpisces** [comment]
Thank you for feedback.

Answer: This is a real issue; _Not all scenario of selector compilation has not been implemented..._

**Comment by sakhram** [comment]
Thanks for the quick response!
Do you have plans to implement it?

Happy Holidays anyway :)

**Comment by wizardpisces** [comment]
Happy Holidays !!!

Answer: Not in plan yet

PS: 
1. This project is mainly for learning of whole compilation process
2. There is already mature [solution](https://github.com/sass/dart-sass) with full test cases
3. PR is always welcomed if you are interested

**Comment by sakhram** [comment]
Thanks for response :)

I tried dart-sass but couldn't import it properly in my angular ts project.
(I use your library for a backoffice to live-compute scss for preview)

Bye!

**Comment by wizardpisces** [comment]
Have you tried this [solution](https://github.com/less/less.js)

**Comment by sakhram** [comment]
I will, thanks :)

**Comment by sakhram** [comment]
Hi,
It workes perfectly with less.js, thanks for the hint!
Happy new year!!

Pierre.
