### ISSUE TITLE
[Question] Can I use it with webpack?

### ISSUE THREAD

**Issue by htdangkhoa** [wizardpisces/tiny-sass-compiler#9]

**Comment by wizardpisces** [comment]
No, because specific webpack plugin is not developed yet; You could use dart-sass or less , they are safe and battle tested codebase;

**Comment by htdangkhoa** [comment]
@wizardpisces thanks for your response, so do you have a plan to create plugins to support any module bundler like Webpack, Rollup.js,...?

**Comment by wizardpisces** [comment]
> @wizardpisces thanks for your response, so do you have a plan to create plugins to support any module bundler like Webpack, Rollup.js,...?

No such plan yet，because [sass-spec](https://github.com/sass/sass-spec) is not fully covered，still needs lots of effort
